config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'top#index'
  resources :players do
    resources :manuals do
      resources :likes, only: [:create, :destroy]
    end
  end
  resources :clubs do
    collection { post :import }
  end
  resources :users
  resources :top, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord
  
  #association
  has_many :users
  has_many :players
  
  def self.import(file)
    CSV.foreach(file.path,encoding: 'SHIFT_JIS:UTF-8', headers: true) do |row|
    # IDが見つかれば、レコードを呼び出し、見つからなければ、新しく作成
    club = find_by(id: row["id"]) || new
    # CSVからデータを取得し、設定する
    club.attributes = row.to_hash.slice(*updatable_attributes)
    # 保存する
    club.save
    end
  end
  
  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["id", "name", "abbreviation", "founding", "join", "detail"]
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :manual
  
  validates_uniqueness_of :manual_id, scope: :user_id
end

app/models/manual.rb
class Manual < ApplicationRecord
  belongs_to :player
  belongs_to :user
  has_many :likes
  
  has_many :liked_users, through: :likes, source: :user
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :manuals
  belongs_to :club
  has_many :users, through: :manuals
  
  
end

app/models/scraping.rb
class Scraping
  
  def self.get_players
    # 更新タイミング
    updated_season = "2020a"
    
    
    # 取得先クラブ検索時のURLを貼り付け
    url = 'https://data.j-league.or.jp/SFIX02/search?displayId=SFIX02&selectValue=1&displayId=SFIX02&selectValueTeam=14&displayName=%EF%BC%AA%EF%BC%91%E3%83%AA%E3%83%BC%E3%82%B0&displayNameTeam=%E5%8C%97%E6%B5%B7%E9%81%93%E3%82%B3%E3%83%B3%E3%82%B5%E3%83%89%E3%83%BC%E3%83%AC%E6%9C%AD%E5%B9%8C'
    
    
    club_id = 1 #Clubsテーブルのidと一致させること
    
    
    n=3
    
    agent = Mechanize.new
    page = agent.get(url)
    
    while true
      #break判定
      check = page.at('//*[@id="contents"]/form/div[3]/div[' + n.to_s + ']/p/span[1]')
      break if check == nil
      
      #checkに要素が存在するまで以下を繰り返し
      #選手名を取得
      name = page.at('//*[@id="contents"]/form/div[3]/div[' + n.to_s + ']/p/span[1]').inner_text
      
      #選手名（英語）を取得
      yomi = page.at('//*[@id="contents"]/form/div[3]/div[' + n.to_s + ']/p/span[2]').inner_text if page.at('//*[@id="contents"]/form/div[3]/div[' + n.to_s + ']/p/span[2]')
    
      #身長体重を取得
      figure = page.at('//*[@id="contents"]/form/div[3]/div[' + n.to_s + ']/dl/dd[3]').inner_text if page.at('//*[@id="contents"]/form/div[3]/div[' + n.to_s + ']/dl/dd[3]')
      
      #ポジションを取得
      position = page.at('//*[@id="contents"]/form/div[3]/div[' + n.to_s + ']/dl/dd[1]').inner_text if page.at('//*[@id="contents"]/form/div[3]/div[' + n.to_s + ']/dl/dd[1]')
      
      #誕生日を取得
      birthday = page.at('//*[@id="contents"]/form/div[3]/div[' + n.to_s + ']/dl/dd[2]').inner_text
      
      #重複チェック用データ作成
      name_birthday = name + birthday
      
      player = Player.where(name_birthday: name_birthday).first_or_initialize
      player.name = name
      player.name_yomi = yomi
      player.club_id = club_id
      player.figure = figure
      player.position = position
      player.birthday = birthday
      
      player.updated_season = updated_season
      
      player.save
      
      n += 1
    end
    
  end
  
  def self.active_check
    
    update = "2020a" #ここにアップデートしたタイミングを記述
    
    id = 1
    
    while Player.last.id > id
      player = Player.find(id)
      
      if player.updated_season == update
        player.update(active_check: true)
      else
        player.update(active_check: false)
      end
      
      id += 1
    end
    
  end

end

app/models/user.rb
class User < ApplicationRecord
  #association
  has_many :manuals, dependent: :destroy
  belongs_to :club, optional: true
  has_many :players, through: :manuals
  has_many :likes, dependent: :destroy
  has_many :liked_manuals, through: :likes, source: :manual
  
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable #:confirmable
         
  def already_liked?(manual)
    self.likes.exists?(manual_id: manual.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  
  def configure_permitted_parameters
    added_attrs = [:club_id, :email, :name, :password, :password_confirmation, :birthday, :detail, :memorial_game]
    devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
    devise_parameter_sanitizer.permit(:account_update, keys: added_attrs)
    devise_parameter_sanitizer.permit(:sign_in, keys: added_attrs)
  end
  
  def after_sign_out_path_for resource
    root_path
  end
  
  def after_sign_in_path_for(resource)
    user_path(resource)
  end
  
  def after_update_path_for(resource)
    user_path
  end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  
  def index
   all_clubs = Club.all
   @clubs_odd = all_clubs.each_slice(2).map(&:first)
   @clubs_even = all_clubs.each_slice(2).map(&:last)
  end
  
  def show
    @club = Club.find(params[:id])
    @players = @club.players
    @gks = @players.where(position: "GK")
    @dfs = @players.where(position: "DF")
    @mfs = @players.where(position: "MF")
    @fws = @players.where(position: "FW")
  end
  
  private
  def import
    # fileはtmpに自動で一時保存される
    Club.import(params[:file])
    redirect_to clubs_url
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @manual = Manual.find(params[:manual_id])
    @like = Like.new(manual_id: params[:manual_id], user_id: current_user.id)
    @like.save
    redirect_to player_path(@manual.player_id)
  end
  
  def destroy
    @manual = Manual.find(params[:manual_id])
    @like = Like.find_by(manual_id: params[:manual_id], user_id: current_user.id)
    @like.destroy
    redirect_to player_path(@manual.player.id)
  end
  
  private
  def like_params
    params.require(:like).permit(:post_id, :user_id)
  end
end

app/controllers/manuals_controller.rb
class ManualsController < ApplicationController
  def new 
    @player = Player.find(params[:player_id])
    @manual = Manual.new
    @manual.player_id = @player.id
  end
  
  def create
    @manual = Manual.create(create_params)
  end
  
  def edit
    @manual = Manual.find(params[:id])
    @player = @manual.player
  end
  
  def update
    manual = Manual.find(params[:id])
    @player = manual.player
    manual.update(update_params)
  end
  
  def destroy
    @manual = Manual.find(params[:id])
    @manual.destroy
  end
  
  private
  def create_params
    params.require(:manual).permit(:player_id, :text).merge(user_id: current_user.id)
  end
  
  def update_params
    params.require(:manual).permit(:text)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def show
    @player = Player.find(params[:id]) #playerテーブルの中で、idが997のインスタンスを取得
    @manuals = @player.manuals.order('updated_at DESC').page(params[:page]).per(5) #取得されたplayerのidとPlayer_idが一致するmanualテーブルのインスタンスを取得
    @like = Like.new()
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  layout 'index'
  
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :move_to_sign_in
  
  def show
    @user = User.find(params[:id])
    @manuals = @user.manuals.includes(:player).order('updated_at DESC').limit(5)
  end
  
  private
  def move_to_sign_in
    redirect_to "/users/sign_in" unless user_signed_in?
  end
  
  def import
    # fileはtmpに自動で一時保存される
    Club.import(params[:file])
    redirect_to user_path(1)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/manuals_helper.rb
module ManualsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clubs/index.html.erb
<div class="contents">
  <div class="main-contents">
    <div class="club-contents">
      <h1>クラブ一覧</h1>
      
      <div class="clubs_info">
        <ul class="odd">
          <% @clubs_odd.each do |club_odd| %>
            <li><%= link_to club_odd.name, club_path(club_odd.id) %></li>
          <% end %>
        </ul>
      
        <ul class="even">
          <% @clubs_even.each do |club_even| %>
            <li><%= link_to club_even.name, club_path(club_even.id) %></li>
          <% end %>
        </ul>
      </div>
    
    </div>
  </div>
</div>

app/views/clubs/show.html.erb
<div class="contents">
  <div class="main-contents">
    <div class="club-contents">
      <div class="favorite_club">
        <% if user_signed_in? %>
          <% if @club.id == current_user.club.id %>
          <span class="favorite_club_title">YOUR CLUB!</span>
          <% end %>
        <% end %>
        <h1><%= @club.name %></h1>
        <!--<p class="detail">みんなのクラブプロフィール</p> -->
        <!--simple format(model.column)で改行を認識させる-->
      </div>
      
      <div class="players">
        <span class="players_title">PLAYERS</span>
        
          <div class="position GK">
            <span class="position_title GK">GK</span>
            <ul>
              <% @gks.each do |gk| %>
                <li><%= link_to gk.name , player_path(gk.id), class:"btn-handwrite" %></li>
              <% end %>
            </ul>
          </div>
          
          <div class="position DF">
            <span class="position_title DF">DF</span>
            <ul>
              <% @dfs.each do |df| %>
                <li><%= link_to df.name , player_path(df.id), class:"btn-handwrite" %></li>
              <% end %>
            </ul>
          </div>
          
          <div class="position MF">
            <span class="position_title MF">MF</span>
            <ul>
              <% @mfs.each do |mf| %>
                <li><%= link_to mf.name , player_path(mf.id), class:"btn-handwrite" %></li>
              <% end %>
            </ul>
          </div>
          
          <div class="position FW">
            <span class="position_title FW">FW</span>
            <ul>
              <% @fws.each do |fw| %>
                <li><%= link_to fw.name , player_path(fw.id), class:"btn-handwrite" %></li>
              <% end %>
            </ul>
          </div>
          
        </div>
        
    </div>
  </div>
</div>

app/views/manuals/create.html.erb
<div class="manuals_create_contents">
  
  <h2>トリセツを投稿しました！</h2>
  <a href="/"></a>
  
</div>

app/views/manuals/destroy.html.erb
<div class="contents">
  <div class="main-contents">
    <div class="manuals_destroy_contents">
      
      <h2>トリセツを削除しました！</h2>
      
      <%= link_to '選手ページにもどる', player_path(@manual.player_id) %>
      
    </div>
  </div>
</div>

app/views/manuals/edit.html.erb
<div class="contents">
  <div class="main-contents">
    <div class="manuals_contents">
      
      <h2><span><%= @player.name %></span>のトリセツを編集</h2>
      <div class="manual_form">
        
        <%= form_for [@player, @manual] do |f| %>
          <div class="manual_text fusen">
            <div class="fusen_content">
              <%= f.text_area :text, placeholder: 'この選手のトリセツを編集！' %>
              <div class="posted_user">
                <span>投稿者:</span><%= current_user.name %>
              </div>
              <div class="submit">
                <%= f.submit "更新！", class: 'btn-handwrite' %>
              </div>
            </div>
          </div>
        <% end %>
        
      </div>
      
      <%= link_to '選手ページにもどる', player_path(@player.id) %>
    </div>
  </div>
</div>

app/views/manuals/new.html.erb
<div class="manuals_new_contents">
  
  <h2>トリセツの投稿</h2>
  <div class="manual_form">
    
    <form action="/manuals" method='post'>
      <div class="fusen">
        <div class="fusen_content">
          <textarea name="text" placeholder="トリセツを書きましょう！" rows="10" cols="70"></textarea>
          <input type="text" name="name" placeholder="名前を入力してください">
        </div>
      </div>
      <input type="submit" value="投稿！">
    </form>
    
  </div>
  
</div>

app/views/manuals/update.html.erb
<div class="contents">
  <div class="main-contents">
    <div class="manuals_update_contents">
      
      <h2>トリセツを更新しました！</h2>
      
      <%= link_to '選手ページにもどる', player_path(@player.id) %>
      
    </div>
  </div>
</div>

app/views/players/show.html.erb
<div class="contents">
  <div class="main-contents">
    <div class="players_show_contents">
      
      <div class="player_show title_card">
        <div class="player_data">
          <h1><%= @player.name %><span>のトリセツ</span></h1>
        </div>
        <div class="fusen">
          <div class="fusen_content">
            <p>ポジション：<%= @player.position %></p>
          </div>
          <div class="fusen_content">
            <p>生年月日：<%= @player.birthday %></p>
          </div>
          <div class="fusen_content">
            <p>身長/体重：<%= @player.figure %></p>
          </div>
        </div>
      </div>
      
      <% if user_signed_in? %>
        <div class="post_button">
          <% if user_signed_in? %>
            <% if current_user.club.id == @player.club.id %>
              <%= link_to "トリセツを投稿する！", new_player_manual_path(@player.id), class:"btn-handwrite" %>
            <% end %>
          <% end %>
        </div>
      <% end %>
      
      <div class="player_manual fusen">
          
        <% @manuals.each do |manual| %>
          <div class="fusen_content">
            <div class="manual_text" >
              <p><%= manual.text %></p>
            </div>
            <% if user_signed_in? %>
              <div class="manual_data">
                <div class="good">
                  <div class="good_btn">
                    <% if current_user.already_liked?(manual) %>
                      <%= link_to player_manual_like_path(manual_id: manual.id, player_id: manual.player.id), method: :delete do %>
                        <i class='fas fa-thumbs-up good_btn_after'></i>
                      <% end %>
                    <% else %>
                      <%= link_to player_manual_likes_path(manual_id: manual.id, player_id: manual.player.id), method: :post do %>
                        <i class='fas fa-thumbs-up good_btn_before'></i>
                      <% end %>
                    <% end %>
                  </div>
                  <div class="good_count">
                    <%= manual.likes.count %>
                  </div>
                </div>
                <div class="posted_user">
                  <p>投稿者: <span><%= link_to manual.user.name, user_path(id: manual.user.id, class:"user_name") %></span></p>
                </div>
                <% if manual.user.id == current_user.id %>
                  <div class="btn">
                    <%= link_to "編集", edit_player_manual_path(player_id: @player.id, id: manual) %>
                  </div>
                  <div class="btn">
                    <%= link_to "削除", player_manual_path(player_id: @player.id, id: manual), method: :delete %>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        <% end %>
        <%= paginate(@manuals) %>
      </div>
      
    </div>
  </div>
</div>

app/views/top/_top.html.erb
<div class="sigin_up_message">
  <h4>ログインすると、トリセツの投稿やユーザー情報の閲覧ができるようになります！</h4>
  <%= link_to '新規登録する！', new_user_registration_path %>
  <%= link_to 'ログインする！', new_user_session_path %>
  
  <%= link_to 'クラブ一覧へ', clubs_path %>
</div>

app/views/top/index.html.erb
<div class="title_book">
  <div class="page_title_card">
    <h1>みんなでつくる</h1>
    <h1>Jのトリセツ</h1>
  </div>
  
  <div class="main_menu">
    <ul>
      <div class="user_session">
        <li><%= link_to 'ログイン', new_user_session_path, class:'btn-handwrite login_btn' %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class:'btn-handwrite signup_btn' %></li>
      </div>
      <li><%= link_to 'ログインせずにトリセツを読む', clubs_path, class:'btn-handwrite read_btn' %></li>
    </ul>
  </div>
</div>

app/views/top/show.html.erb
<div class="top-contents">
  
</div>

app/views/users/show.html.erb
<div class="contents">
  <div class="main-contents">
    <div class="users_show_contents">
      
    <% if user_signed_in? %>
      <div class="user_show title_card">
        <div class="user_name">
          <h1><%= @user.name %><span>のページ</span></h1>
        </div>
      </div>
      
      <% if current_user.id == @user.id %>
        <div class="news">
          <span class="news_title">最近の投稿</span>
            <ul>
            <% @manuals.each do |manual| %>
              <li><%= link_to manual.player.name + "のトリセツ", player_path(manual.player.id) %>　(<%= manual.updated_at.strftime("%Y-%m-%d %H:%M") %>)</li>
            <% end %>
            </ul>
        </div>
      <% end %>
      
      <div class="edit_button">
        <% if user_signed_in? %>
          <% if current_user.id == @user.id %>
            <%= link_to "ユーザー情報を変更", edit_user_registration_path(@user.id), class:"btn-handwrite" %>
          <% end %>
        <% end %>
      </div>
      
      <div class="user_manual">
        
        <div class="user_club">
          <h4>私のお気に入りクラブ</h4>
          <% if @user.club %>
            <p><%= link_to @user.club.name, club_path(@user.club.id), class:"club_btn" %>
          <% else %>
            <p>未設定</p>
          <% end %>
        </div>
        
        <div class="user_detail">
          <h4>このページを見てくれている方へ</h4>
          <% if @user.detail %>
            <div class="fusen">
              <div class="fusen_content">
                <p><%= @user.detail %></p>
              </div>
            </div>
          <% else %>
          <% end %>
        </div>
        
        <div class="user_birthday">
          <h4>誕生日</h4>
          <% if @user.birthday %>
            <div class="fusen">
              <div class="fusen_content">
                <p><%= @user.birthday %></p>
              </div>
            </div>
          <% end %>
        </div>
        
        <div class="user_memorial_game">
          <h4>思い出の試合</h4>
          <% if @user.memorial_game %>
            <div class="fusen">
              <div class="fusen_content">
                <p><%= @user.memorial_game %></p>
              </div>
            </div>
          <% end %>
        </div>
        
      </div>
    
      <% if current_user.admin? %>
        <div class="admin_contents">
          <%= form_tag import_clubs_path, multipart: true do %>
            <%= file_field_tag :file %>
            <%= submit_tag "インポート" %>
          <% end %>
        </div>
      <% end %>
      
    <% else %>
      <% redirect_to root_path %>
    
    <% end %>  
    </div>
  </div>
</div>